# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='demoappointment',
            old_name='user_id',
            new_name='user',
        ),
    ]
