# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calenders', '0002_auto_20170514_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caleder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
