# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0003_usercalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalender',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercalender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caleder', to=settings.AUTH_USER_MODEL),
        ),
    ]
